//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication5.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HealthTrackDB2 : DbContext
    {
        public HealthTrackDB2()
            : base("name=HealthTrackDB2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<alimen> alimen { get; set; }
        public virtual DbSet<Altura> Altura { get; set; }
        public virtual DbSet<Atividade> Atividade { get; set; }
        public virtual DbSet<Comida> Comida { get; set; }
        public virtual DbSet<NutricionistasParcas> NutricionistasParcas { get; set; }
        public virtual DbSet<Peso> Peso { get; set; }
        public virtual DbSet<PressaoArterial> PressaoArterial { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    }
}
